print("------------------------")
print("¡¡¡Bienvenido HINCHAAA!!!")
print("Veamos Como Estamos")
print("------------------------")
print("")
equipo=input("Que equipo vamos a seguir: ")
print("------------------------")
print("Genial")
print("------------------------")
a=3*int(input("Cuantos partidos gano hasta ahora: "))
a=a+int(input("y cuantos empatamos?: "))
print("------------------------")
print(f"Entonces {equipo} lleva acumulado {a} puntos hasta ahora")
print("------------------------")