print("------------------------")
print("Bienvenido alumno")
print("------------------------")
print("")
a=int(input("Ingrese la primer nota: "))
a=a+int(input("Ingrese la segunda nota: "))
a=a+int(input("Ingrese la tercer nota: "))
a=a+int(input("Ingrese la cuarta nota: "))
a=a+int(input("Ingrese la quinta nota: "))
a = a/5
print("")
print("------------------------")
print(f'Su promedio es: {a}')
print("------------------------")
print("")