print("------------------------")
print("Bienvenido")
print("------------------------")
print("")
a=float(input("Por favor, ingrese la altura de la pared: "))
a=a*float(input("Por favor, ingrese el ancho de la pared: "))
a=a*float(input("Por favor, ingrese el costo por m2: "))
print("")
print("------------------------")
print(f'Su costo total es de :$ {a}')
print("------------------------")
print("")